---
version: '3'
services:
  postgresql-employee:
    image: postgres:12
    container_name: pg-employee
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: uberpopug
      POSTGRES_HOST_AUTH_METHOD: trust
  postgresql-task:
    image: postgres:12
    container_name: pg-task
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: uberpopug
      POSTGRES_HOST_AUTH_METHOD: trust
  postgresql-accounting:
    image: postgres:12
    container_name: pg-accounting
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: uberpopug
      POSTGRES_HOST_AUTH_METHOD: trust
  postgresql-analytics:
    image: postgres:12
    container_name: pg-analytics
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: uberpopug
      POSTGRES_HOST_AUTH_METHOD: trust
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:latest
    tty: true
    stdin_open: true
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
