spring:
  application:
    name: uberpopug
  profiles:
    active: ${APP_PROFILE:default}
  main:
    banner-mode: off
  jpa:
    properties:
      hibernate:
        generate_statistics: true
  datasource:
    hikari:
      idle-timeout: 10000
      connection-timeout: 1000
      maximum-pool-size: 5
      pool-name: ${spring.application.name}
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5434}/${DB_NAME:uberpopug}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pwd}
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 4
      missing-topics-fatal: false
      ack-mode: manual_immediate
    producer:
      client-id: acounting-service
    consumer:
      auto-offset-reset: latest
  security:
    oauth2:
      client:
        registration:
          auth-client:
            client-id: accounting-app
            client-secret: NuSRtmhGmAGL42CaxQB9fDw7Mpkk5czH
            client-name: Auth Server
            scope: user_info
            provider: auth-app
            redirect-uri: http://localhost:8083/login/oauth2/code/
            authorization-grant-type: authorization_code
            client-authentication-method: basic
        provider:
          auth-app:
            authorization-uri: http://localhost:8081/oauth/authorize
            token-uri: http://localhost:8081/oauth/token
            user-info-uri: http://localhost:8081/user/me
            user-name-attribute: name

server:
  port: 8083
  servlet:
    session:
      cookie:
        name: UISESSION
