spring:
  application:
    name: uberpopug
  profiles:
    active: ${APP_PROFILE:default}
  main:
    banner-mode: off
  jpa:
    properties:
      hibernate:
        generate_statistics: true
  datasource:
    hikari:
      idle-timeout: 10000
      connection-timeout: 1000
      maximum-pool-size: 5
      pool-name: ${spring.application.name}
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5432}/${DB_NAME:uberpopug}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pwd}
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      concurrency: 4
      missing-topics-fatal: false
      ack-mode: manual_immediate
    producer:
      client-id: employee-service
    consumer:
      auto-offset-reset: latest

server:
  port: 8081

oauth:
  clients:
    -
      client-id: task-app
      client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
      authorized-grand-types: authorization_code
      scope: user_info
      approve: true
      redirect-url: http://localhost:8082/login/oauth2/code/
    -
      client-id: accounting-app
      client-secret: NuSRtmhGmAGL42CaxQB9fDw7Mpkk5czH
      authorized-grand-types: authorization_code
      scope: user_info
      approve: true
      redirect-url: http://localhost:8083/login/oauth2/code/
    -
      client-id: analytics-app
      client-secret: 5czHNuSRtmhGmAGL42CaxQB9fDw7Mpkk
      authorized-grand-types: authorization_code
      scope: user_info
      approve: true
      redirect-url: http://localhost:8084/login/oauth2/code/
