spring:
  thymeleaf:
    cache: false
  application:
    name: uberpopug
  profiles:
    active: ${APP_PROFILE:default}
  main:
    banner-mode: off
  jpa:
    properties:
      hibernate:
        generate_statistics: true
  datasource:
    hikari:
      idle-timeout: 10000
      connection-timeout: 1000
      maximum-pool-size: 5
      pool-name: ${spring.application.name}
    url: jdbc:postgresql://${DB_HOST:127.0.0.1}:${DB_PORT:5433}/${DB_NAME:uberpopug}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:pwd}

  security:
    oauth2:
      client:
        registration:
          auth-client:
            client-id: R2dpxQ3vPrtfgF72
            client-secret: fDw7Mpkk5czHNuSRtmhGmAGL42CaxQB9
            client-name: Auth Server
            scope: user_info
            provider: auth-app
            redirect-uri: http://localhost:8082/login/oauth2/code/
            authorization-grant-type: authorization_code
            client-authentication-method: basic
        provider:
          auth-app:
            authorization-uri: http://localhost:8081/auth/oauth/authorize
            token-uri: http://localhost:8081/auth/oauth/token
            user-info-uri: http://localhost:8081/auth/user/me
            user-name-attribute: name

server:
  port: 8082
  servlet:
    session:
      cookie:
        name: UISESSION
